version: "3.3"

services: 
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  postgres:
    image: postgres:13-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cryptoapp
  redis:
    image: redis:latest

  notify:
    build:
      context: .
      dockerfile: notify/Dockerfile
    ports: 
      - 8081:8081
    environment: 
      - JWT_PRIVATE_PATH=rsa/key.pem
      - JWT_PUBLIC_PATH=rsa/public.pem
      - PORT=8081
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password 
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - GMAIL_SMTP_PORT=587
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - GMAIL_SMTP=smtp.gmail.com
    depends_on: 
      - rabbitmq
      - account

    entrypoint: ["/notify/wait_for.sh", "rabbitmq:5672", "account:8080", "--", "/notify/start.sh"]
    command: ["/notify/notify"]
    
  account:
    build:
      dockerfile: account/Dockerfile
      context: .
    environment: 
      - DB_HOST=postgres
      - DB_DRIVER=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password 
      - DB_NAME=cryptoapp
      - DB_PORT=5432
      - JWT_PRIVATE_PATH=rsa/key.pem
      - JWT_PUBLIC_PATH=rsa/public.pem
      - PORT=8080
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on: 
      - postgres
      - rabbitmq
    entrypoint: ["/account/wait_for.sh", "postgres:5432", "rabbitmq:5672", "--", "/account/start.sh"]
    command: ["/account/account"]

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - cryptoapp.com
    volumes:
      - ./nginx/services/services.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/ca-cert.pem:/etc/nginx/certs/ca-cert.pem
      - ./nginx/certs/server-key.pem:/etc/nginx/certs/server-key.pem
      - ./wait_for.sh:/wait_for.sh
    depends_on: 
      - account
      - notify
