version: "3.3"
services: 
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  postgres:
    image: postgres:13-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cryptoapp

  notify:
    build:
      context: .
      dockerfile: notify/Dockerfile
    ports:
      - "8081:8081"
    environment: 
      - JWT_PRIVATE_PATH=rsa/key.pem
      - JWT_PUBLIC_PATH=rsa/public.pem
      - PORT=8081
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - GMAIL_SMTP_PORT=587
      - GMAIL_EMAIL=winwisely100@gmail.com
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - GMAIL_SMTP=smtp.gmail.com
    depends_on: 
      - rabbitmq
      - account

    entrypoint: ["/notify/wait_for.sh", "rabbitmq:5672", "account:8080", "--", "/notify/start.sh"]
    command: ["/notify/notify"]
    
  account:
    build:
      context: .
      dockerfile: account/Dockerfile
    ports:
      - "8080:8080"    
    environment: 
      - DB_HOST=postgres
      - DB_DRIVER=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=cryptoapp
      - DB_PORT=5432
      - JWT_PRIVATE_PATH=rsa/key.pem
      - JWT_PUBLIC_PATH=rsa/public.pem
      - PORT=8080
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on: 
      - postgres
      - rabbitmq
    entrypoint: ["/account/wait_for.sh", "postgres:5432", "rabbitmq:5672", "--", "/account/start.sh"]
    command: ["/account/account"]