// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// IMemoryStore is an autogenerated mock type for the IMemoryStore type
type IMemoryStore struct {
	mock.Mock
}

// GetLoginAttemps provides a mock function with given fields: key
func (_m *IMemoryStore) GetLoginAttemps(key string) (int, error) {
	ret := _m.Called(key)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLoginAttemps provides a mock function with given fields: key, value, exp
func (_m *IMemoryStore) SetLoginAttemps(key string, value int, exp time.Duration) error {
	ret := _m.Called(key, value, exp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, time.Duration) error); ok {
		r0 = rf(key, value, exp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
