apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: account
  template:
    metadata:
      labels:
        component: account
    spec:
      initContainers:
        - name: init-account
          image: busybox:1.28
          command: ['sh', '-c', 'echo The app is running! && sleep 10']     
      restartPolicy: Always  
      containers:
        - name: account
          image: gcr.io/gateway-282214/account
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_DRIVER
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password
                  key: DB_PASSWORD
            - name: DB_NAME
              value: cryptoapp
            - name: DB_PORT
              value: '5432'
            - name: JWT_PRIVATE_PATH
              value: rsa/key.pem
            - name: JWT_PUBLIC_PATH
              value: rsa/public.pem
            - name: PORT
              value: '8080'
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: RABBITMQ_PORT
              value: '5672'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_HOST
              value: redis-service
            
              
