// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/idirall22/crypto_app/account/service/model"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// ActivateAccount provides a mock function with given fields: ctx, args
func (_m *IRepository) ActivateAccount(ctx context.Context, args model.ActivateAccountParams) (model.User, error) {
	ret := _m.Called(ctx, args)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, model.ActivateAccountParams) model.User); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.ActivateAccountParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, args
func (_m *IRepository) GetUser(ctx context.Context, args model.GetUserParams) (model.User, error) {
	ret := _m.Called(ctx, args)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, model.GetUserParams) model.User); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GetUserParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWallet provides a mock function with given fields: ctx, args
func (_m *IRepository) GetWallet(ctx context.Context, args model.GetWalletParams) (model.Wallet, error) {
	ret := _m.Called(ctx, args)

	var r0 model.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, model.GetWalletParams) model.Wallet); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(model.Wallet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GetWalletParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletByAddress provides a mock function with given fields: ctx, args
func (_m *IRepository) GetWalletByAddress(ctx context.Context, args model.GetWalletParams) (model.Wallet, error) {
	ret := _m.Called(ctx, args)

	var r0 model.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, model.GetWalletParams) model.Wallet); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(model.Wallet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GetWalletParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTransactions provides a mock function with given fields: ctx, args
func (_m *IRepository) ListTransactions(ctx context.Context, args model.ListTransactionsParams) ([]model.Transaction, error) {
	ret := _m.Called(ctx, args)

	var r0 []model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, model.ListTransactionsParams) []model.Transaction); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.ListTransactionsParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWallets provides a mock function with given fields: ctx, args
func (_m *IRepository) ListWallets(ctx context.Context, args model.ListWalletsParams) ([]model.Wallet, error) {
	ret := _m.Called(ctx, args)

	var r0 []model.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, model.ListWalletsParams) []model.Wallet); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.ListWalletsParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: ctx, args
func (_m *IRepository) RegisterUser(ctx context.Context, args model.RegisterUserParams) (model.User, error) {
	ret := _m.Called(ctx, args)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(context.Context, model.RegisterUserParams) model.User); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.RegisterUserParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMoney provides a mock function with given fields: ctx, args
func (_m *IRepository) SendMoney(ctx context.Context, args model.SendMoneyParams) (model.Transaction, error) {
	ret := _m.Called(ctx, args)

	var r0 model.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, model.SendMoneyParams) model.Transaction); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Get(0).(model.Transaction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.SendMoneyParams) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
