// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IEmail is an autogenerated mock type for the IEmail type
type IEmail struct {
	mock.Mock
}

// EmailRegisterUserConfirmation provides a mock function with given fields: email, firstName, confirmationLink
func (_m *IEmail) EmailRegisterUserConfirmation(email string, firstName string, confirmationLink string) error {
	ret := _m.Called(email, firstName, confirmationLink)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(email, firstName, confirmationLink)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
