name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    
    - run: |-
        gcloud --quiet auth configure-docker
    
    - name: Build account container
      run: docker build -f account/Dockerfile -t gcr.io/${{ secrets.GKE_PROJECT }}/account .
      working-directory: .
    
    - name: Build notify container
      run: docker build -f notify/Dockerfile -t gcr.io/${{ secrets.GKE_PROJECT }}/notify .
      working-directory: .
    
    - name: docker-login
	    run: echo ${{ secrets.GKE_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
      working-directory: .
    
    - name: push containers to gcp
      run: |
        docker push "gcr.io/${{ secrets.GKE_PROJECT }}/notify"
	      docker push "gcr.io/${{ secrets.GKE_PROJECT }}/account"

    