name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    needs: test
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    
    - run: |-
        gcloud --quiet auth configure-docker
    
    - name: Build account container
      run: docker build -f account/Dockerfile -t gcr.io/${{ secrets.GKE_PROJECT }}/account .
      working-directory: .
    
    - name: Build notify container
      run: docker build -f notify/Dockerfile -t gcr.io/${{ secrets.GKE_PROJECT }}/notify .
      working-directory: .
      
    - name: Configure docker for GCP
      run: gcloud auth configure-docker
    
    - name: push account container to gcp
      run: docker push "gcr.io/${{ secrets.GKE_PROJECT }}/account"
    
    - name: push notify container to gcp
      run: docker push "gcr.io/${{ secrets.GKE_PROJECT }}/notify"
    
    # - name: setup gcloud
    #   run: |-
    #     gcloud config set compute/zone europe-west3-a
    #     gcloud container clusters get-credentials cryptoapp
    # - name: deply to k8s
    #   run: ./deploy.sh